services:
  web:
    image: nginx:latest
    container_name: my_simple_nginx
    ports:
    - "8080:80" # Map host port 8080 to container's port 8081
    volumes:
    - ./html:/usr/share/nginx/html:z # Mount local html directory
    - ./config/nginx.conf:/etc/nginx.conf # Mount local nginx.conf

    restart: unless-stopped
